name: JukeBukkit
main: cc.thedudeguy.jukebukkit.JukeBukkit
version: 0.3
description: Allows you to "Burn" new music onto Music Discs and play them in the Jukeboxes.
author: Chris Churchwell (thedudeguy)
website: https://github.com/thedudeguy/JukeBukkit
depend: [Spout]
commands:
    jukebukkit:
        aliases: [cd]
permissions:
    jukebukkit.*:
        description: Gives access to all jukebukkit commands
        children:
            jukebukkit.burn: true
            jukebukkit.edit: true
            jukebukkit.clone: true
    jukebukkit.burn:
        description: Allows a user to burn new cds
        default: true
    jukebukkit.edit:
        description: Allows a user to edit cd title and artist without being the creator of the cd
        default: op
    jukebukkit.clone:
        description: Allows discs to be cloned
        default: op