name: JukeBukkit
main: cc.thedudeguy.jukebukkit.JukeBukkit
version: 1.3-pre
description: Burn music on disc (Obsidyiscs) and play them in many different types of jukeboxes.
author: Chris Churchwell (thedudeguy)
website: http://dev.bukkit.org/server-mods/jukebukkit/
depend: [Spout]