name: JukeIt
main: com.chrischurchwell.jukeit.JukeIt
version: ${version}
description: Burn music on disc (Obsidyiscs) and play them in many different types of jukeboxes.
author: Chris Churchwell (thedudeguy)
website: http://chrischurchwell.com
depend: [Spout]
database: true
commands:
  jukeit:
    description: All commands are subsidized from the main command /jukeit
    aliases: juke
    usage: Use "/jukeit help" for more information
permissions:
  jukeit.command.resetcache:
    description: Gives access to the resetcache command
    default: op
  jukeit.command.discinfo:
    description: Gives access to the discinfo command
    default: op
  jukeit.command.givedisc:
    description: Gives access to the givedisc command
    default: op
  jukeit.command.listurls:
    description: Gives access to the listurls command
    default: op
  jukeit.craft.needle:
    description: Access to craft needles
    default: true
  jukeit.craft.blankdisc:
    description: Access to craft blank discs
    default: true
  jukeit.craft.burner:
    description: Access to craft disc burner
    default: true
  jukeit.craft.wire:
    description: Access to craft speaker wire
    default: true
  jukeit.craft.jukebox:
    description: Access to craft jukeboxes
    default: true
  jukeit.craft.jukebox.world:
    description: Access to craft world range jukebox
    default: op
  jukeit.craft.machinepart:
    description: Access to craft machine parts
    default: true
  jukeit.craft.machine:
    description: Access to craft machine out of parts
    default: true
  jukeit.craft.speaker:
    description: Access to craft speakers
    default: true
  jukeit.craft.recordplayer:
    description: Access to craft record player
    default: true
  jukeit.craft.machine:
    description: Access to craft disc machine
    default: true
  jukeit.use.needle:
    description: Ability to attach/detach needles
    default: true
  jukeit.use.blankdisc:
    description: Ability to burn discs
    default: true
  jukeit.use.burneddisc:
    description: Ability to insert/eject burned discs
    default: true
  jukeit.use.burner:
    description: Access to use disc burner
    default: true
  jukeit.use.jukebox:
    description: Access to craft jukeboxes
    default: true
  jukeit.use.recordplayer:
    description: Access to play recordplayers by punching
    default: true
  jukeit.use.jukebox.world:
    description: Access to use world range jukeboxes
    default: op
  jukeit.use.machine:
    description: Access to use machine
    default: true
