name: JukeBukkit
main: cc.thedudeguy.jukebukkit.JukeBukkit
version: 1.6.1
description: Burn music on disc (Obsidyiscs) and play them in many different types of jukeboxes.
author: Chris Churchwell (thedudeguy)
website: http://dev.bukkit.org/server-mods/jukebukkit/
depend: [Spout]
database: true
commands:
  jukebukkit:
    description: All commands are subsidized from the main command /jukebukkit
    aliases: jb
    usage: Use "/jukebukkit help" for more information
permissions:
  jukebukkit.command.resetcache:
    description: Gives access to the resetcache command
    default: op